class Exclusion:
    """
    qwewqewq
    """

    binaries = ["mkl_core.2.dll"
                "mkl_avx512.2.dll"
                "mkl_pgi_thread.2.dll"
                "mkl_mc3.2.dll"
                "mkl_avx2.2.dll"
                "mkl_intel_thread.2.dll"
                "mkl_def.2.dll"
                "mkl_tbb_thread.2.dll"
                "libblas.dll"
                "libcblas.dll"
                "liblapack.dll"
                "mkl_rt.2.dll"
                "mkl_sequential.2.dll"
                "mkl_vml_avx512.2.dll"
                "mkl_vml_avx2.2.dll"
                "mkl_vml_mc3.2.dll"
                "mkl_vml_def.2.dll"
                "mkl_vml_cmpt.2.dll"
                "mkl_scalapack_ilp64.2.dll"
                "mkl_scalapack_lp64.2.dll"]