name: Release DeepLabCut

on:
  push:
    tags: ['deeplabcut-v*']
  workflow_dispatch:

permissions:
  contents: write  # needed to create GitHub Releases

concurrency:
  group: dlc-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: [self-hosted, Windows, X64, GPU]
    timeout-minutes: 180

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version from tag
        shell: powershell
        run: |
          $version = "$env:GITHUB_REF_NAME".Replace("deeplabcut-v","")
          "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding ascii

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true

      - name: Create env
        shell: powershell
        run: conda create -n dlc_pyinstaller python=3.10 -y

      - name: Install deps from requirements + GPU Torch
        shell: powershell
        run: |
          conda run -n dlc_pyinstaller python -m pip install --upgrade pip
          conda run -n dlc_pyinstaller pip install -r DeepLabCut/requirements.txt
          # ensure pyinstaller is present (remove if it's already in your requirements)
          conda install -n dlc_pyinstaller -y -c conda-forge pyinstaller
          # force CUDA build of torch
          conda run -n dlc_pyinstaller pip install --upgrade --index-url https://download.pytorch.org/whl/cu124 torch torchvision
          # sanity check
          conda run -n dlc_pyinstaller python - << 'PY'
          import torch, sys
          print("Torch:", torch.__version__)
          print("CUDA build:", getattr(torch.version, "cuda", None))
          print("CUDA available at runtime:", torch.cuda.is_available())
          PY

      - name: Build DeepLabCut exe (PyInstaller)
        shell: powershell
        working-directory: Deploy
        run: |
          conda run -n dlc_pyinstaller pyinstaller --clean --noconfirm pack_deeplabcut_run.spec
          Compress-Archive -Path dist\* -DestinationPath ("DeepLabCut-" + $env:VERSION + ".zip")

      - name: Create GitHub Release (attach zip)
        uses: softprops/action-gh-release@v2
        with:
          name: DeepLabCut ${{ env.VERSION }}
          body: "Automated DeepLabCut release for tag ${{ github.ref_name }}."
          files: Deploy/DeepLabCut-${{ env.VERSION }}.zip
