name: Release DeepLabCut

on:
  push:
    tags: ['deeplabcut-v*']
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: dlc-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: [self-hosted, Windows, X64, GPU]
    timeout-minutes: 180

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version from tag (cmd)
        shell: cmd
        run: |
          set VERSION=%GITHUB_REF_NAME:deeplabcut-v=%
          echo VERSION=%VERSION%>> %GITHUB_ENV%

      - name: Create venv (cmd)
        shell: cmd
        run: |
          C:\Python310\python.exe -V
          C:\Python310\python.exe -m venv venv

      - name: Install deps (cmd)
        shell: cmd
        run: |
          venv\Scripts\python -m pip install --upgrade pip
          venv\Scripts\pip install h5py pyinstaller deeplabcut==3.0.0rc8
          venv\Scripts\pip install --upgrade --index-url https://download.pytorch.org/whl/cu126 torch torchvision
          venv\Scripts\python -c "import torch;print('Torch:',torch.__version__);print('CUDA build:',getattr(torch.version,'cuda',None));print('CUDA available:',torch.cuda.is_available())"

      - name: Clean old dist/build (cmd)
        shell: cmd
        working-directory: Deploy
        run: |
          if exist dist rmdir /s /q dist
          if exist build rmdir /s /q build

      - name: Build deeplabcut (cmd)
        shell: cmd
        working-directory: Deploy
        run: |
          ..\venv\Scripts\pyinstaller --clean --noconfirm pack_deeplabcut_run.spec
          echo === DIST TREE ===
          dir /s /b dist

      - name: Zip onedir output with build-info (cmd)
        shell: cmd
        working-directory: Deploy
        env:
          GIT_SHA: ${{ github.sha }}
        run: |
          rem Locate the onedir app folder under dist
          set "APPDIR="
          for /d %%D in (dist\*) do (
            set "APPDIR=%%D"
            goto :found
          )
          :found
          if not defined APPDIR (
            echo ERROR: no onedir folder found in Deploy\dist
            exit /b 1
          )

          rem Create build-info.txt inside the app folder so it goes into the zip
          echo Version: %VERSION%> "%APPDIR%\build-info.txt"
          echo Commit: %GIT_SHA%>> "%APPDIR%\build-info.txt"
          echo Date: %DATE% %TIME%>> "%APPDIR%\build-info.txt"

          rem Zip the app folder contents
          set ZIPNAME=deeplabcut-%VERSION%.zip
          echo Zipping contents of %APPDIR% into %ZIPNAME%
          tar -a -c -f %ZIPNAME% -C "%APPDIR%" .
          echo Created zip: %ZIPNAME%

      - name: SHA256 of release zip (cmd)
        shell: cmd
        working-directory: Deploy
        run: |
          setlocal EnableDelayedExpansion
          set ZIP=deeplabcut-%VERSION%.zip
          for /f "usebackq skip=1 tokens=1" %%H in (`certutil -hashfile "%ZIP%" SHA256 ^| findstr /v /i "hash certutil"`) do (
            set HASH=%%H
            goto :got
          )
          :got
          echo !HASH!> deeplabcut-%VERSION%.zip.sha256
          type deeplabcut-%VERSION%.zip.sha256

      - name: Create GitHub Release (attach zip + checksum)
        uses: softprops/action-gh-release@v2
        with:
          name: deeplabcut ${{ env.VERSION }}
          body: |
            Automated deeplabcut release for tag ${{ github.ref_name }}.
            - Version: ${{ env.VERSION }}
            - Commit: ${{ github.sha }}
          files: |
            Deploy/deeplabcut-${{ env.VERSION }}.zip
            Deploy/deeplabcut-${{ env.VERSION }}.zip.sha256

      - name: Copy release zip to server (cmd)
        shell: cmd
        working-directory: Deploy
        env:
          DLC_BACKUP_ROOT: \\SRV2019-AD\Labo\Internal Software\danse\Libraries\DeepLabCut
        run: |
          set "ZIPNAME=deeplabcut-%VERSION%.zip"
          set "ZIPPATH=%CD%\%ZIPNAME%"

          if not exist "%ZIPPATH%" (
            echo ERROR: Release zip not found: "%ZIPPATH%"
            exit /b 1
          )

          if not exist "%DLC_BACKUP_ROOT%" (
            echo ERROR: Backup root is not reachable: "%DLC_BACKUP_ROOT%"
            exit /b 1
          )

          echo Copying "%ZIPPATH%" to "%DLC_BACKUP_ROOT%\%ZIPNAME%"
          copy /Y "%ZIPPATH%" "%DLC_BACKUP_ROOT%\%ZIPNAME%" >nul || (echo ERROR: copy failed & exit /b 1)
          echo Backup zip is at: "%DLC_BACKUP_ROOT%\%ZIPNAME%"

      # Upload heavy dist only if something failed (short retention)
      - name: Upload dist artifact (only on failure)
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: deeplabcut-dist-${{ env.VERSION }}
          path: Deploy/dist/**
          retention-days: 3
          compression-level: 1
